version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl
  settings:
    lll:
      line-length: 100
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustivestruct
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(gitlab.com/SensysGatso)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
