# See https://pre-commit.com for more information
exclude: "vendor|mocks"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint-full
        args: ["--timeout=2m"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint-fix
        language_version: 14.19.1
